/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router. this part to trigger deployment another trigger haha one more rao
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NewsRouteImport } from './routes/news'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWorkshopRouteImport } from './routes/services.workshop'
import { Route as ServicesTrackingRouteImport } from './routes/services.tracking'
import { Route as ServicesTechnicalRouteImport } from './routes/services.technical'
import { Route as ServicesSpecialRouteImport } from './routes/services.special'
import { Route as ServicesK9RouteImport } from './routes/services.k9'
import { Route as ServicesHomeSecurityRouteImport } from './routes/services.home-security'
import { Route as ServicesGuardingRouteImport } from './routes/services.guarding'
import { Route as ServicesCctvRouteImport } from './routes/services.cctv'
import { Route as ServicesAlarmResponseRouteImport } from './routes/services.alarm-response'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWorkshopRoute = ServicesWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTrackingRoute = ServicesTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTechnicalRoute = ServicesTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSpecialRoute = ServicesSpecialRouteImport.update({
  id: '/special',
  path: '/special',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesK9Route = ServicesK9RouteImport.update({
  id: '/k9',
  path: '/k9',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHomeSecurityRoute = ServicesHomeSecurityRouteImport.update({
  id: '/home-security',
  path: '/home-security',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGuardingRoute = ServicesGuardingRouteImport.update({
  id: '/guarding',
  path: '/guarding',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCctvRoute = ServicesCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAlarmResponseRoute = ServicesAlarmResponseRouteImport.update({
  id: '/alarm-response',
  path: '/alarm-response',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/csr': typeof CsrRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/alarm-response': typeof ServicesAlarmResponseRoute
  '/services/cctv': typeof ServicesCctvRoute
  '/services/guarding': typeof ServicesGuardingRoute
  '/services/home-security': typeof ServicesHomeSecurityRoute
  '/services/k9': typeof ServicesK9Route
  '/services/special': typeof ServicesSpecialRoute
  '/services/technical': typeof ServicesTechnicalRoute
  '/services/tracking': typeof ServicesTrackingRoute
  '/services/workshop': typeof ServicesWorkshopRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/csr': typeof CsrRoute
  '/news': typeof NewsRoute
  '/services/alarm-response': typeof ServicesAlarmResponseRoute
  '/services/cctv': typeof ServicesCctvRoute
  '/services/guarding': typeof ServicesGuardingRoute
  '/services/home-security': typeof ServicesHomeSecurityRoute
  '/services/k9': typeof ServicesK9Route
  '/services/special': typeof ServicesSpecialRoute
  '/services/technical': typeof ServicesTechnicalRoute
  '/services/tracking': typeof ServicesTrackingRoute
  '/services/workshop': typeof ServicesWorkshopRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/csr': typeof CsrRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/alarm-response': typeof ServicesAlarmResponseRoute
  '/services/cctv': typeof ServicesCctvRoute
  '/services/guarding': typeof ServicesGuardingRoute
  '/services/home-security': typeof ServicesHomeSecurityRoute
  '/services/k9': typeof ServicesK9Route
  '/services/special': typeof ServicesSpecialRoute
  '/services/technical': typeof ServicesTechnicalRoute
  '/services/tracking': typeof ServicesTrackingRoute
  '/services/workshop': typeof ServicesWorkshopRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contacts'
    | '/csr'
    | '/news'
    | '/services'
    | '/services/alarm-response'
    | '/services/cctv'
    | '/services/guarding'
    | '/services/home-security'
    | '/services/k9'
    | '/services/special'
    | '/services/technical'
    | '/services/tracking'
    | '/services/workshop'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contacts'
    | '/csr'
    | '/news'
    | '/services/alarm-response'
    | '/services/cctv'
    | '/services/guarding'
    | '/services/home-security'
    | '/services/k9'
    | '/services/special'
    | '/services/technical'
    | '/services/tracking'
    | '/services/workshop'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contacts'
    | '/csr'
    | '/news'
    | '/services'
    | '/services/alarm-response'
    | '/services/cctv'
    | '/services/guarding'
    | '/services/home-security'
    | '/services/k9'
    | '/services/special'
    | '/services/technical'
    | '/services/tracking'
    | '/services/workshop'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ClientsRoute: typeof ClientsRoute
  ContactsRoute: typeof ContactsRoute
  CsrRoute: typeof CsrRoute
  NewsRoute: typeof NewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/workshop': {
      id: '/services/workshop'
      path: '/workshop'
      fullPath: '/services/workshop'
      preLoaderRoute: typeof ServicesWorkshopRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tracking': {
      id: '/services/tracking'
      path: '/tracking'
      fullPath: '/services/tracking'
      preLoaderRoute: typeof ServicesTrackingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/technical': {
      id: '/services/technical'
      path: '/technical'
      fullPath: '/services/technical'
      preLoaderRoute: typeof ServicesTechnicalRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/special': {
      id: '/services/special'
      path: '/special'
      fullPath: '/services/special'
      preLoaderRoute: typeof ServicesSpecialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/k9': {
      id: '/services/k9'
      path: '/k9'
      fullPath: '/services/k9'
      preLoaderRoute: typeof ServicesK9RouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/home-security': {
      id: '/services/home-security'
      path: '/home-security'
      fullPath: '/services/home-security'
      preLoaderRoute: typeof ServicesHomeSecurityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/guarding': {
      id: '/services/guarding'
      path: '/guarding'
      fullPath: '/services/guarding'
      preLoaderRoute: typeof ServicesGuardingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cctv': {
      id: '/services/cctv'
      path: '/cctv'
      fullPath: '/services/cctv'
      preLoaderRoute: typeof ServicesCctvRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/alarm-response': {
      id: '/services/alarm-response'
      path: '/alarm-response'
      fullPath: '/services/alarm-response'
      preLoaderRoute: typeof ServicesAlarmResponseRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAlarmResponseRoute: typeof ServicesAlarmResponseRoute
  ServicesCctvRoute: typeof ServicesCctvRoute
  ServicesGuardingRoute: typeof ServicesGuardingRoute
  ServicesHomeSecurityRoute: typeof ServicesHomeSecurityRoute
  ServicesK9Route: typeof ServicesK9Route
  ServicesSpecialRoute: typeof ServicesSpecialRoute
  ServicesTechnicalRoute: typeof ServicesTechnicalRoute
  ServicesTrackingRoute: typeof ServicesTrackingRoute
  ServicesWorkshopRoute: typeof ServicesWorkshopRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAlarmResponseRoute: ServicesAlarmResponseRoute,
  ServicesCctvRoute: ServicesCctvRoute,
  ServicesGuardingRoute: ServicesGuardingRoute,
  ServicesHomeSecurityRoute: ServicesHomeSecurityRoute,
  ServicesK9Route: ServicesK9Route,
  ServicesSpecialRoute: ServicesSpecialRoute,
  ServicesTechnicalRoute: ServicesTechnicalRoute,
  ServicesTrackingRoute: ServicesTrackingRoute,
  ServicesWorkshopRoute: ServicesWorkshopRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ClientsRoute: ClientsRoute,
  ContactsRoute: ContactsRoute,
  CsrRoute: CsrRoute,
  NewsRoute: NewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
